const USER_INFO = 'USER_INFO';
const SIGN_UP = 'SIGN_UP';
const PAYMENT = 'PAYMENT';
const LOGOUT = 'LOGOUT';
const NAVIGATOR_TAB = 'NAVIGATOR_TAB';
const SELECT_CATEGORY = 'SELECT_CATEGORY';
const UPDATE_DISTANCE = 'UPDATE_DISTANCE';
const ORDER = 'ORDER';
const CHART = 'CHART';
const ALL_ORDER = 'ALL_ORDER';
const RATING = 'RATING';


export { 
	USER_INFO,
	SIGN_UP,
	PAYMENT,
	LOGOUT,
	SELECT_CATEGORY,
	NAVIGATOR_TAB,
	UPDATE_DISTANCE,
    ORDER,
	CHART,
	ALL_ORDER,
	RATING,
}