const USER_INFO = 'USER_INFO';
const SIGN_UP = 'SIGN_UP';
const PAYMENT = 'PAYMENT';
const LOGOUT = 'LOGOUT';
const NAVIGATOR_TAB = 'NAVIGATOR_TAB';
const SELECT_CATEGORY = 'SELECT_CATEGORY';
const UPDATE_DISTANCE = 'UPDATE_DISTANCE';

export { 
	USER_INFO,
	SIGN_UP,
	PAYMENT,
	LOGOUT,
	SELECT_CATEGORY,
	NAVIGATOR_TAB,
	UPDATE_DISTANCE
}